### ISSUE TITLE
Missing Sapien map type strings.

### ISSUE THREAD

**Issue by General-101** [Himanshu-01/H2Codez#16]
Sapien is missing the strings for the map type as seen here.

https://i.imgur.com/r3ezRl7.png

Looking at H2alang.DLL one can find the strings here in ResourceHacker you can find the strings.

https://i.imgur.com/sdIpUF2.png

`310, 	"\000Single Player"
312, 	"Multiplayer"
314, 	"\000Main Menu"
316, 	"\000Multiplayer Shared"
318, 	"\000Single Player Shared"`

According to Ale(Num0005), the \000 means that the string is commented out and thus shows empty in the editor. If we simply remove the \000 and save the DLL like so...

`310, 	"Single Player"
312, 	"Multiplayer"
314, 	"Main Menu"
316, 	"Multiplayer Shared"
318, 	"Single Player Shared"`

We now get this when using Sapien.

https://i.imgur.com/ZyqwD33.png

Getting this into H2Codez would be helpful for users.

**Comment by General-101** [comment]
Just tested Ale's(Num0005) commit in both debug and release. Works perfectly on my end. Waiting on pull request to close the issue.

**Comment by Himanshu-01** [comment]
Sure I will do it
