### ISSUE TITLE
Guerilla script length

### ISSUE THREAD

**Issue by General-101** [Himanshu-01/H2Codez#19]
The default amount of maximum characters allows in a script is pretty short. Scripts like the one linked below do not fit into the editor. In order to get around this we use a program called H2V Script Maker. This helps us make longer scripts than what is normally allowed in default H2Guerilla. Even default scripts from the campaign do not even fit into the script entry and will be cut off. I would like to see this be changed so that we can type much longer scripts inside the editor. Scripts made with the H2V Script Maker will work fine. They will even display fine when you open them in Guerilla. They will be cut down to back 4098 bytes if you attempt to edit them in Guerilla though.

https://pastebin.com/rafaUuqW
http://www.h2mt.org/tools/2_Vista/Scripts/H2V%20Scripting%20Maker/1.1/
https://i.imgur.com/DCL1jsr.png

**Comment by num0005** [comment]
Fixed, Guerilla should now support the theoretical maximum of 0x40000 bytes for script tags.
