### ISSUE TITLE
Model-render will crash if import file is located in the my documents tag folder

### ISSUE THREAD

**Issue by General-101** [Himanshu-01/H2Codez#41]
Leaving this here so that people are aware if someone else asks.
Any import files used to build a render_model that are located in

C:\Users\(USERNAME)\Documents\Halo 2\tags

will cause h2tool.exe to crash as soon as it has finished building the scenario_structure_bsp. I'm assuming the cause for this is as soon as the first step is finished it then attempts to locate the file which is not in the place it expected it to be. All render_models should be built from their standard location in program files for the time being.

**Comment by num0005** [comment]
Fixed after rewrite.
