### ISSUE TITLE
Character tags do not get their dependencies added

### ISSUE THREAD

**Issue by General-101** [Himanshu-01/H2Codez#43]
This issue affects maps packaged with a character tag. Character tags unlike any other tags will not have their dependencies added to the tag under seemingly no circumstances. Attempts to use the tag shared removal or hex editing shared to change the name of the resource it looks for does not resolve the issue. 

This is somewhat important as this tag controls the properties of the AI such as what weapons they can fire and how they fire them. Current animation swap requires a custom generic.character parent tag and because of this AI on maps will not fire until references to the weapons are added manually in Assembly. 
For an example of this issue compare generic.char in a default shared.map to a compiled generic.char in a custom firefight map.

**Comment by num0005** [comment]
Seems this is intentional on the part of bungie, some tag refs don't add the tags they reference unless something else does.
