### ISSUE TITLE
Lighting maps with multiple pc's

### ISSUE THREAD

**Issue by Berthalamew** [Himanshu-01/H2Codez#52]
Wondering if the functionality of compiling the lightmaps over multiple Pc's like Bungie did with their "light farms" is still in the h2tool's and if so could be brought back or could be reworked to make the tool use multiple cores to help speed up lighting times when compiling maps on super or on higher lightmap resolutions.

**Comment by bigtweekx** [comment]
buy an i9-9900k https://www.cpubenchmark.net/singleThread.html

**Comment by num0005** [comment]
Using multiple processes is possible as of fe4d61e28d71ef79e0f46fea693cbf9a8b192f10, now you can figure out how to build a server farm for this.
