### ISSUE TITLE
Blender object scales not converting correctly

### ISSUE THREAD

**Issue by jtzfusion** [Himanshu-01/H2Codez#53]
I'm new to making custom H2 maps. I followed the blender tutorial here: [https://github.com/Project-Cartographer/H2Codez/wiki/Blender-Map-Making-Tutorial.](url), but I'm having a problem. Somewhere between the process of extracting the .blend file as a .ass, and converting the .ass with h2tool, the dimensions of my objects are changing. I'm just working with basic cube shapes right now, but if I set the scale of the cube in blender to 10x10x5 for example, the scenario that opens in Sapien is never that same dimension. Sometimes it's a perfect cube, 10x10x10. Sometimes the scales get stretched in the opposite direction too, making it appear as a 10x10x30 cube.

Here's a test where I have one flat cube, and one tall cube in blender. After extracting and converting, and opening it in Sapien, the flat cube is now tall, and the tall cube is now a perfect cube. Does anybody know what could be happening here?

Any help is appreciated :)

![issue1](https://user-images.githubusercontent.com/48740653/54653273-78909c80-4a90-11e9-8348-41154d2c635d.png)
![issue2](https://user-images.githubusercontent.com/48740653/54653274-78909c80-4a90-11e9-82e4-be3fba563d91.png)

**Comment by General-101** [comment]
Apply the rotation & scale using ctrl+a then try again

**Comment by jtzfusion** [comment]
> Apply the rotation & scale using ctrl+a then try again

Thank you! It looks like this fixed my issue! I'm a little rusty in blender and I forgot about applying changes to rotation, scaling, and position.
