### ISSUE TITLE
Script issues

### ISSUE THREAD

**Issue by General-101** [Himanshu-01/H2Codez#57]
Issues that prevent scripts from SP maps from just working that go beyond missing assets.

**ai_current_actor**
appears to be a command script related function. Somehow gets the name of the squad through the squads that get this command script assigned to them?

**points**
cs_go_nearest has cases where only the point set name is used instead of the point name and then a specific point. This doesn't seem to be accepted by the compiler. Is there something where tool randomly selects a point or where the game randomly does this?

**Script Size**
Acts strange when it reaches the default campaign script size. Starts cutting off a small portion at the end and it can be worked around by adding extra lines.

**cs_movement_mode short**
Compiler doesn't accept this. I'll need to look into what this is later.

**ai_combat_status ai**
This script function is used to return an integer and that is usually used in an if statement to see if the AI is active and do something. However it is comparing integers and the scripts use words like ai_combat_status_active. Is there sentences with assigned levels to them that the original toolset understood?

**Comment by num0005** [comment]
Will need to see the compiled script/syntax node to do anything about a lot of these issues.

**Comment by num0005** [comment]
Closing as the problems that aren't fixed have their own issues open.
