### ISSUE TITLE
Crash with tag sync enabled and no existing tags folder in documents

### ISSUE THREAD

**Issue by General-101** [Himanshu-01/H2Codez#66]
How to reproduce 

Delete the tags folder in documents or just delete the Halo 2 folder in documents in general

Have tag sync enabled

Attempt to open Sapien

[h2sapien.exe_20190810-175008.zip](https://github.com/Project-Cartographer/H2Codez/files/3489359/h2sapien.exe_20190810-175008.zip)

**Comment by num0005** [comment]
DebugDiag Report
![image](https://user-images.githubusercontent.com/30047358/62827712-ac4d9980-bbcc-11e9-8751-f672f62fc060.png)

**Comment by num0005** [comment]
![image](https://user-images.githubusercontent.com/30047358/62827730-0cdcd680-bbcd-11e9-996b-02cd3950fedc.png)
so if I just catch the exception it should be fine.

**Comment by num0005** [comment]
fixed in 7b289c1
