### ISSUE TITLE
Overly complicated shader view

### ISSUE THREAD

**Issue by General-101** [Himanshu-01/H2Codez#7]
The current shader editor in H2Codez I assume was part of Korns plan to change the shader system in Sapien to somehow used compiled shader files from the extracted maps. Either way the current system we have in place makes things really complicated for no reason. If you comment out line 38 and 39 in H2Guerilla.cpp like so.

	// Disable Tag Template Views
	//BYTE k_mod_bytes[0x3] = { 0x33, 0xC0, 0xC3 }; // xor eax, eax; retn
	//WriteBytesASM(0x48E730, k_mod_bytes, 0x3);

This disables the more advanced shader view and returns it to its vanilla form. I would prefer that this would be changed to be something we can enable much like expert mode in Guerilla. Something where the default view is the vanilla shader template system we use and a drop down menu to enable advanced shader editing to view the more complicated shader outline. This is because the extracted shader files still have data that can only be viewed here and is useful for remaking the shader files properly.

**Comment by Himanshu-01** [comment]
Not a bad idea though , thanks for suggestion!
