### ISSUE TITLE
Sound functions

### ISSUE THREAD

**Issue by General-101** [Himanshu-01/H2Codez#8]
As you may or may not know, H2Guerilla has issues with managing sounds Most of the sound related options in the sound tag cause H2Guerilla to crash due to I assume the code behind handling how to do that missing. My suggestion is for someone to somehow port over sound related workings from H1Guerilla into H2Codez. As you also may or may not know we use Halo 1 tool to convert sounds for Halo 2. Normally these sounds would not work out of the box if compiled in H1tool, but if you compile it with an Xbox codec using a linked pack below you can get a result that is compatible with H2EK. Most of the options you can use to edit said sound in H1Guerilla also seem to affect H2Guerilla. It would also be beneficial to also try bringing over the sound import function for H2tool since it has worked so far to bring over sounds. This would be a fantastic step forward as we can begin to phase out the usage of H1tools. This codec pack can also be used to play sounds in H2Guerilla when placed in the bin folder.

https://mega.nz/#!YwsEwbTB!fBE5nZ_2f4XHhVlhvVJmwVa5Fgiy4oGHWwA5UphmNSM

**Comment by Himanshu-01** [comment]
Oh I didn't know that
Atm Working on fixing the  import sound process for h2tool ,and soon will proceed over guerilla. Though I hope Num would know the h2guerilla working

**Comment by General-101** [comment]
Disabling tag template view resolves the crash.
